/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 152a6ca04cfcd2b62d7c9cf752496777)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
