-- Generated from seeds/problems.json. Do not edit by hand.
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (1, 'beginner', '#web-app', 'サトウ', 'PR #12 のレビューお願いできますか？', '確認します。少々お待ちください。', 'かくにんします。しょうしょうおまちください。', '[{"display":"確認","reading":"かくにん"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"少々","reading":"しょうしょう"},{"display":"お待ち","reading":"おまち"},{"display":"ください","reading":"ください"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (2, 'beginner', '#web-app', 'タナカ', 'ログインボタン押しても反応ないです', '再現します。一旦リサーチします…（5分）', 'さいげんします。いったんりさーちします…（5ふん）', '[{"display":"再現","reading":"さいげん"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"一旦","reading":"いったん"},{"display":"リサーチ","reading":"りさーち"},{"display":"します","reading":"します"},{"display":"…","reading":"…"},{"display":"（","reading":"（"},{"display":"5","reading":"5"},{"display":"分","reading":"ふん"},{"display":"）","reading":"）"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (3, 'beginner', '#web-app', 'サトウ', '今日の進捗どう？', 'チケット2件クローズしました。快調です！', 'ちけっと2けんくろーずしました。かいちょうです！', '[{"display":"チケット","reading":"ちけっと"},{"display":"2","reading":"2"},{"display":"件","reading":"けん"},{"display":"クローズ","reading":"くろーず"},{"display":"しました","reading":"しました"},{"display":"。","reading":"。"},{"display":"快調","reading":"かいちょう"},{"display":"です","reading":"です"},{"display":"！","reading":"！"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (4, 'beginner', '#web-app', 'タナカ', 'ステージングのURLってどこでしたっけ', '後で共有します。ブックマーク迷子です…', 'あとできょうゆうします。ぶっくまーくまいごです…', '[{"display":"後で","reading":"あとで"},{"display":"共有","reading":"きょうゆう"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"ブックマーク","reading":"ぶっくまーく"},{"display":"迷子","reading":"まいご"},{"display":"です","reading":"です"},{"display":"…","reading":"…"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (5, 'beginner', '#web-app', 'サトウ', '明日の朝会、出られますか？', '参加します。アラームは3つセット済みです。', 'さんかします。あらーむは3つせっとすみです。', '[{"display":"参加","reading":"さんか"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"アラーム","reading":"あらーむ"},{"display":"は","reading":"は"},{"display":"3","reading":"3"},{"display":"つ","reading":"つ"},{"display":"セット","reading":"せっと"},{"display":"済み","reading":"すみ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (6, 'beginner', '#web-app', 'タナカ', 'テスト環境、誰か使ってます？', '今は空いてます。占有しません、たぶん。', 'いまはあいてます。せんゆうしません、たぶん。', '[{"display":"今は","reading":"いまは"},{"display":"空いてます","reading":"あいてます"},{"display":"。","reading":"。"},{"display":"占有","reading":"せんゆう"},{"display":"しません","reading":"しません"},{"display":"、","reading":"、"},{"display":"たぶん","reading":"たぶん"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (7, 'beginner', '#customer-success', 'CS-ヤマダ', '顧客からログイン方法の確認です', '手順を送ります。パスワードは忘れがちですよね…僕もです。', 'てじゅんをおくります。ぱすわーどはわすれがちですよね…ぼくもです。', '[{"display":"手順","reading":"てじゅん"},{"display":"を","reading":"を"},{"display":"送ります","reading":"おくります"},{"display":"。","reading":"。"},{"display":"パスワード","reading":"ぱすわーど"},{"display":"は","reading":"は"},{"display":"忘れがち","reading":"わすれがち"},{"display":"ですよね","reading":"ですよね"},{"display":"…","reading":"…"},{"display":"僕も","reading":"ぼくも"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (8, 'beginner', '#web-app', 'サトウ', 'README、更新お願い', '直します。絵文字は控えめにします…たぶん。', 'なおします。えもじはひかえめにします…たぶん。', '[{"display":"直します","reading":"なおします"},{"display":"。","reading":"。"},{"display":"絵文字","reading":"えもじ"},{"display":"は","reading":"は"},{"display":"控えめに","reading":"ひかえめに"},{"display":"します","reading":"します"},{"display":"…","reading":"…"},{"display":"たぶん","reading":"たぶん"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (9, 'beginner', '#random', 'タナカ', '今日のランチどうする？', '会議室で食べます。デバッグしながらです。', 'かいぎしつでたべます。でばっぐしながらです。', '[{"display":"会議室","reading":"かいぎしつ"},{"display":"で","reading":"で"},{"display":"食べます","reading":"たべます"},{"display":"。","reading":"。"},{"display":"デバッグ","reading":"でばっぐ"},{"display":"しながら","reading":"しながら"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (10, 'beginner', '#web-app', 'サトウ', 'デプロイ、今日いけそう？', 'いけます。念のためバックアップします…心の。', 'いけます。ねんのためばっくあっぷします…こころの。', '[{"display":"いけます","reading":"いけます"},{"display":"。","reading":"。"},{"display":"念のため","reading":"ねんのため"},{"display":"バックアップ","reading":"ばっくあっぷ"},{"display":"します","reading":"します"},{"display":"…","reading":"…"},{"display":"心の","reading":"こころの"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (11, 'beginner', '#incident', 'タナカ', 'ステージング落ちてない？', '見ます。コーヒーより先に確認します。', 'みます。こーひーよりさきにかくにんします。', '[{"display":"見ます","reading":"みます"},{"display":"。","reading":"。"},{"display":"コーヒー","reading":"こーひー"},{"display":"より","reading":"より"},{"display":"先に","reading":"さきに"},{"display":"確認","reading":"かくにん"},{"display":"します","reading":"します"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (12, 'beginner', '#web-app', 'サトウ', '変数名、もう少し分かりやすくしてほしい', 'リネームします。i とか j は卒業します。', 'りねーむします。i とか j はそつぎょうします。', '[{"display":"リネーム","reading":"りねーむ"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"i ","reading":"i "},{"display":"とか","reading":"とか"},{"display":" j ","reading":" j "},{"display":"は","reading":"は"},{"display":"卒業","reading":"そつぎょう"},{"display":"します","reading":"します"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (13, 'intermediate', '#web-app', 'サトウ', '@オオダ PR #123 レビューまだ？今日中希望です', '@サトウ 確認中です。LGTM狙いで見ます。コーヒーブレイク後には返します。', '@さとう かくにんちゅうです。LGTMねらいでみます。こーひーぶれいくごにはかえします。', '[{"display":"@","reading":"@"},{"display":"サトウ","reading":"さとう"},{"display":" ","reading":" "},{"display":"確認中","reading":"かくにんちゅう"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"LGTM","reading":"LGTM"},{"display":"狙い","reading":"ねらい"},{"display":"で","reading":"で"},{"display":"見ます","reading":"みます"},{"display":"。","reading":"。"},{"display":"コーヒーブレイク","reading":"こーひーぶれいく"},{"display":"後には","reading":"ごには"},{"display":"返します","reading":"かえします"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (14, 'intermediate', '#incident', 'タナカ', '本番で 500 出てます。Issue #88 切りました', 'オンコール的に見ます。再現手順ください。僕のせいだったら餅つきします。', 'おんこーるてきにみます。さいげんてじゅんください。ぼくのせいだったらもちつきします。', '[{"display":"オンコール","reading":"おんこーる"},{"display":"的に","reading":"てきに"},{"display":"見ます","reading":"みます"},{"display":"。","reading":"。"},{"display":"再現","reading":"さいげん"},{"display":"手順","reading":"てじゅん"},{"display":"ください","reading":"ください"},{"display":"。","reading":"。"},{"display":"僕の","reading":"ぼくの"},{"display":"せいだったら","reading":"せいだったら"},{"display":"餅つき","reading":"もちつき"},{"display":"します","reading":"します"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (15, 'intermediate', '#customer-success', 'CS-ヤマダ', '顧客から「保存できない」と。優先度高でお願いします', '了解です。
- 対象: 保存API
- 暫定: リトライ
デバッグしながら盛って直します。', 'りょうかいです。
- たいしょう: ほぞんAPI
- ざんてい: りとらい
でばっぐしながらもってなおします。', '[{"display":"了解","reading":"りょうかい"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"対象","reading":"たいしょう"},{"display":": ","reading":": "},{"display":"保存","reading":"ほぞん"},{"display":"API","reading":"API"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"暫定","reading":"ざんてい"},{"display":": ","reading":": "},{"display":"リトライ","reading":"りとらい"},{"display":"\n","reading":"\n"},{"display":"デバッグ","reading":"でばっぐ"},{"display":"しながら","reading":"しながら"},{"display":"盛って","reading":"もって"},{"display":"直します","reading":"なおします"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (16, 'intermediate', '#web-app', 'サトウ', 'リリース作業の見積もり教えて', '2時間バッファ込みです。フラグは `enable_new_form` 。余裕のフルスタックです。', '2じかんばっふぁこみです。ふらぐは `enable_new_form` 。よゆうのふるすたっくです。', '[{"display":"2","reading":"2"},{"display":"時間","reading":"じかん"},{"display":"バッファ","reading":"ばっふぁ"},{"display":"込み","reading":"こみ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"フラグ","reading":"ふらぐ"},{"display":"は","reading":"は"},{"display":" `","reading":" `"},{"display":"enable_new_form","reading":"enable_new_form"},{"display":"` ","reading":"` "},{"display":"。","reading":"。"},{"display":"余裕の","reading":"よゆうの"},{"display":"フルスタック","reading":"ふるすたっく"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (17, 'intermediate', '#web-app', 'タナカ', '@オオダ CI 落ちてる。test_login だけ赤', '@タナカ フレークかもです。再実行しつつ原因ハントします。僕の環境だけ緑、あるあるです。', '@たなか ふれーくかもです。さいじっこうしつつげんいんはんとします。ぼくのかんきょうだけみどり、あるあるです。', '[{"display":"@","reading":"@"},{"display":"タナカ","reading":"たなか"},{"display":" ","reading":" "},{"display":"フレーク","reading":"ふれーく"},{"display":"かもです","reading":"かもです"},{"display":"。","reading":"。"},{"display":"再実行","reading":"さいじっこう"},{"display":"しつつ","reading":"しつつ"},{"display":"原因","reading":"げんいん"},{"display":"ハント","reading":"はんと"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"僕の","reading":"ぼくの"},{"display":"環境","reading":"かんきょう"},{"display":"だけ","reading":"だけ"},{"display":"緑","reading":"みどり"},{"display":"、","reading":"、"},{"display":"あるあるです","reading":"あるあるです"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (18, 'intermediate', '#customer-success', 'CS-ヤマダ', 'クライアントAから「画面が白い」と連絡。優先で。', 'ブランク画面ですね。キャッシュ疑いで見ます。白すぎて雪だるまかと思いました。', 'ぶらんくがめんですね。きゃっしゅうたがいでみます。しろすぎてゆきだるまかとおもいました。', '[{"display":"ブランク","reading":"ぶらんく"},{"display":"画面","reading":"がめん"},{"display":"ですね","reading":"ですね"},{"display":"。","reading":"。"},{"display":"キャッシュ","reading":"きゃっしゅ"},{"display":"疑い","reading":"うたがい"},{"display":"で","reading":"で"},{"display":"見ます","reading":"みます"},{"display":"。","reading":"。"},{"display":"白すぎて","reading":"しろすぎて"},{"display":"雪だるま","reading":"ゆきだるま"},{"display":"かと","reading":"かと"},{"display":"思いました","reading":"おもいました"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (19, 'intermediate', '#web-app', 'サトウ', '@オオダ Issue #45 の見積もり、今日中にコメントして', '@サトウ 3ポイントで入れてます。バッファは「祈りの1日」です。', '@さとう 3ぽいんとでいれてます。ばっふぁは「いのりの1にち」です。', '[{"display":"@","reading":"@"},{"display":"サトウ","reading":"さとう"},{"display":" ","reading":" "},{"display":"3","reading":"3"},{"display":"ポイント","reading":"ぽいんと"},{"display":"で","reading":"で"},{"display":"入れてます","reading":"いれてます"},{"display":"。","reading":"。"},{"display":"バッファ","reading":"ばっふぁ"},{"display":"は","reading":"は"},{"display":"「","reading":"「"},{"display":"祈り","reading":"いのり"},{"display":"の","reading":"の"},{"display":"1","reading":"1"},{"display":"日","reading":"にち"},{"display":"」","reading":"」"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (20, 'intermediate', '#incident', 'タナカ', 'ログが `timeout` だらけ。誰か一次切り分けを', 'アラート確認しました。ボトルネックは DB 接続です。僕のハートビートは正常です。', 'あらーとかくにんしました。ぼとるねっくは DB せつぞくです。ぼくのはーとびーとはせいじょうです。', '[{"display":"アラート","reading":"あらーと"},{"display":"確認","reading":"かくにん"},{"display":"しました","reading":"しました"},{"display":"。","reading":"。"},{"display":"ボトルネック","reading":"ぼとるねっく"},{"display":"は","reading":"は"},{"display":" DB ","reading":" DB "},{"display":"接続","reading":"せつぞく"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"僕の","reading":"ぼくの"},{"display":"ハートビート","reading":"はーとびーと"},{"display":"は","reading":"は"},{"display":"正常","reading":"せいじょう"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (21, 'intermediate', '#web-app', 'サトウ', 'PR #77 コンフリクトしてます。マージお願い', 'リベースします。コンフリクト解消は筋肉です。たぶん精神の。', 'りべーすします。こんふりくとかいしょうはきんにくです。たぶんせいしんの。', '[{"display":"リベース","reading":"りべーす"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"コンフリクト","reading":"こんふりくと"},{"display":"解消","reading":"かいしょう"},{"display":"は","reading":"は"},{"display":"筋肉","reading":"きんにく"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"たぶん","reading":"たぶん"},{"display":"精神の","reading":"せいしんの"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (22, 'intermediate', '#customer-success', 'クライアントA', '仕様書の最新版、共有いただけますか？', '本日中に送ります。バージョンは `spec_v3` です。ページ数より熱量で勝負してます。', 'ほんじつちゅうにおくります。ばーじょんは `spec_v3` です。ぺーじすうよりねつりょうでしょうぶしてます。', '[{"display":"本日中に","reading":"ほんじつちゅうに"},{"display":"送ります","reading":"おくります"},{"display":"。","reading":"。"},{"display":"バージョン","reading":"ばーじょん"},{"display":"は","reading":"は"},{"display":" `","reading":" `"},{"display":"spec_v3","reading":"spec_v3"},{"display":"` ","reading":"` "},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"ページ","reading":"ぺーじ"},{"display":"数より","reading":"すうより"},{"display":"熱量","reading":"ねつりょう"},{"display":"で","reading":"で"},{"display":"勝負してます","reading":"しょうぶしてます"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (23, 'intermediate', '#random', 'タナカ', 'キーボード壊れた。備品申請って誰？', '@タナカ 総務です。ホットスワップ推奨。キーが飛んだら心も飛びます。', '@たなか そうむです。ほっとすわっぷすいしょう。きーがとんだらこころもとびます。', '[{"display":"@","reading":"@"},{"display":"タナカ","reading":"たなか"},{"display":" ","reading":" "},{"display":"総務","reading":"そうむ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"ホットスワップ","reading":"ほっとすわっぷ"},{"display":"推奨","reading":"すいしょう"},{"display":"。","reading":"。"},{"display":"キー","reading":"きー"},{"display":"が","reading":"が"},{"display":"飛んだら","reading":"とんだら"},{"display":"心も","reading":"こころも"},{"display":"飛びます","reading":"とびます"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (24, 'intermediate', '#web-app', 'サトウ', 'ステージングに `feat/login` 乗せて確認お願い', 'デプロイ済みです。スモークテストから入ります。火は出してません、まだ。', 'でぷろいすみです。すもーくてすとからはいります。ひはだしてません、まだ。', '[{"display":"デプロイ","reading":"でぷろい"},{"display":"済み","reading":"すみ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"スモークテスト","reading":"すもーくてすと"},{"display":"から","reading":"から"},{"display":"入ります","reading":"はいります"},{"display":"。","reading":"。"},{"display":"火は","reading":"ひは"},{"display":"出してません","reading":"だしてません"},{"display":"、","reading":"、"},{"display":"まだ","reading":"まだ"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (25, 'advanced', '#incident', 'サトウ', '決済が落ちてます。顧客から怒りのメンション来てます', '> 決済が落ちてます

原因は timeout と判断。PR #402 で retry 入れます。
- 暫定: キュー再投入
- 恒久: タイムアウト延長

僕が出るとインシデントが静かにします。たぶん。', '> けっさいがおちてます

げんいんは timeout とはんだん。PR #402 で retry いれます。
- ざんてい: きゅーさいとうにゅう
- こうきゅう: たいむあうとえんちょう

ぼくがでるといんしでんとがしずかにします。たぶん。', '[{"display":"> ","reading":"> "},{"display":"決済","reading":"けっさい"},{"display":"が","reading":"が"},{"display":"落ちてます","reading":"おちてます"},{"display":"\n\n","reading":"\n\n"},{"display":"原因","reading":"げんいん"},{"display":"は","reading":"は"},{"display":" timeout ","reading":" timeout "},{"display":"と","reading":"と"},{"display":"判断","reading":"はんだん"},{"display":"。","reading":"。"},{"display":"PR #402","reading":"PR #402"},{"display":" で ","reading":" で "},{"display":"retry","reading":"retry"},{"display":" ","reading":" "},{"display":"入れます","reading":"いれます"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"暫定","reading":"ざんてい"},{"display":": ","reading":": "},{"display":"キュー","reading":"きゅー"},{"display":"再投入","reading":"さいとうにゅう"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"恒久","reading":"こうきゅう"},{"display":": ","reading":": "},{"display":"タイムアウト","reading":"たいむあうと"},{"display":"延長","reading":"えんちょう"},{"display":"\n\n","reading":"\n\n"},{"display":"僕が","reading":"ぼくが"},{"display":"出ると","reading":"でると"},{"display":"インシデント","reading":"いんしでんと"},{"display":"が","reading":"が"},{"display":"静かに","reading":"しずかに"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"たぶん","reading":"たぶん"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (26, 'advanced', '#web-app', 'タナカ', '@オオダ N+1 疑いで遅延してる。誰か見て', '@タナカ 既にプロファイリング済みです。
`User.includes(:orders)` で解消予定。
ベンチは 1.8s → 120ms。神です。僕が。', '@たなか すでにぷろふぁいりんぐすみです。
`User.includes(:orders)` でかいしょうよてい。
べんちは 1.8s → 120ms。かみです。ぼくが。', '[{"display":"@","reading":"@"},{"display":"タナカ","reading":"たなか"},{"display":" ","reading":" "},{"display":"既に","reading":"すでに"},{"display":"プロファイリング","reading":"ぷろふぁいりんぐ"},{"display":"済み","reading":"すみ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"`","reading":"`"},{"display":"User.includes(:orders)","reading":"User.includes(:orders)"},{"display":"`","reading":"`"},{"display":" で","reading":" で"},{"display":"解消","reading":"かいしょう"},{"display":"予定","reading":"よてい"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"ベンチ","reading":"べんち"},{"display":"は","reading":"は"},{"display":" 1.8s → 120ms","reading":" 1.8s → 120ms"},{"display":"。","reading":"。"},{"display":"神です","reading":"かみです"},{"display":"。","reading":"。"},{"display":"僕が","reading":"ぼくが"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (27, 'advanced', '#customer-success', 'CS-ヤマダ', '顧客向けの謝罪文ドラフトお願いします。今日中', '件名: 障害のお詫び
本文:
ご迷惑をおかけし申し訳ございません。
現在は復旧済みです。再発防止をコミットします。
（社内向け: 盛ってないです。今回は本当です）', 'けんめい: しょうがいのおわび
ほんぶん:
ごめいわくをおかけしもうしわけございません。
げんざいはふっきゅうすみです。さいはつぼうしをこみっとします。
（しゃないむけ: もってないです。こんかいはほんとうです）', '[{"display":"件名","reading":"けんめい"},{"display":": ","reading":": "},{"display":"障害の","reading":"しょうがいの"},{"display":"お詫び","reading":"おわび"},{"display":"\n","reading":"\n"},{"display":"本文","reading":"ほんぶん"},{"display":":","reading":":"},{"display":"\n","reading":"\n"},{"display":"ご迷惑を","reading":"ごめいわくを"},{"display":"おかけし","reading":"おかけし"},{"display":"申し訳","reading":"もうしわけ"},{"display":"ございません","reading":"ございません"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"現在は","reading":"げんざいは"},{"display":"復旧","reading":"ふっきゅう"},{"display":"済み","reading":"すみ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"再発防止","reading":"さいはつぼうし"},{"display":"を","reading":"を"},{"display":"コミット","reading":"こみっと"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"（","reading":"（"},{"display":"社内向け","reading":"しゃないむけ"},{"display":": ","reading":": "},{"display":"盛ってないです","reading":"もってないです"},{"display":"。","reading":"。"},{"display":"今回は","reading":"こんかいは"},{"display":"本当です","reading":"ほんとうです"},{"display":"）","reading":"）"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (28, 'advanced', '#incident', 'サトウ', '本番のメモリが 95%。今すぐ見て', 'ヒープダンプ取ります。GC チューニングが先です。
- 暫定: レプリカ増やす
- 恒久: リーク潰し

僕のRAMは無限です。サーバーはそうでもない。', 'ひーぷだんぷとります。GC ちゅーにんぐがさきです。
- ざんてい: れぷりかふやす
- こうきゅう: りーくつぶし

ぼくのRAMはむげんです。さーばーはそうでもない。', '[{"display":"ヒープダンプ","reading":"ひーぷだんぷ"},{"display":"取ります","reading":"とります"},{"display":"。","reading":"。"},{"display":"GC ","reading":"GC "},{"display":"チューニング","reading":"ちゅーにんぐ"},{"display":"が","reading":"が"},{"display":"先です","reading":"さきです"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"暫定","reading":"ざんてい"},{"display":": ","reading":": "},{"display":"レプリカ","reading":"れぷりか"},{"display":"増やす","reading":"ふやす"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"恒久","reading":"こうきゅう"},{"display":": ","reading":": "},{"display":"リーク","reading":"りーく"},{"display":"潰し","reading":"つぶし"},{"display":"\n\n","reading":"\n\n"},{"display":"僕の","reading":"ぼくの"},{"display":"RAM","reading":"RAM"},{"display":"は","reading":"は"},{"display":"無限","reading":"むげん"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"サーバー","reading":"さーばー"},{"display":"は","reading":"は"},{"display":"そうでもない","reading":"そうでもない"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (29, 'advanced', '#web-app', 'タナカ', '@オオダ GraphQL の N+1、また出てない？', '@タナカ DataLoader で潰します。
クエリは `users { posts { comments } }` 想定。
バッチ化しないと夜も眠れない。僕は眠い。', '@たなか DataLoader でつぶします。
くえりは `users { posts { comments } }` そうてい。
ばっちかしないとよるもねむれない。ぼくはねむい。', '[{"display":"@","reading":"@"},{"display":"タナカ","reading":"たなか"},{"display":" ","reading":" "},{"display":"DataLoader","reading":"DataLoader"},{"display":" で","reading":" で"},{"display":"潰します","reading":"つぶします"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"クエリ","reading":"くえり"},{"display":"は","reading":"は"},{"display":" `","reading":" `"},{"display":"users { posts { comments } }","reading":"users { posts { comments } }"},{"display":"` ","reading":"` "},{"display":"想定","reading":"そうてい"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"バッチ","reading":"ばっち"},{"display":"化しないと","reading":"かしないと"},{"display":"夜も","reading":"よるも"},{"display":"眠れない","reading":"ねむれない"},{"display":"。","reading":"。"},{"display":"僕は","reading":"ぼくは"},{"display":"眠い","reading":"ねむい"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (30, 'advanced', '#customer-success', 'クライアントA', '障害の根本原因と再発防止、資料化してください', 'RCA まとめます。
- トリガー: デプロイ窓
- 対策: カナリア + ロールバック手順

ポストモーテムは盛らずに書きます。自信だけ盛ります。', 'RCA まとめます。
- とりがー: でぷろいまど
- たいさく: かなりあ + ろーるばっくてじゅん

ぽすともーてむはもらずにかきます。じしんだけもります。', '[{"display":"RCA ","reading":"RCA "},{"display":"まとめます","reading":"まとめます"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"トリガー","reading":"とりがー"},{"display":": ","reading":": "},{"display":"デプロイ","reading":"でぷろい"},{"display":"窓","reading":"まど"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"対策","reading":"たいさく"},{"display":": ","reading":": "},{"display":"カナリア","reading":"かなりあ"},{"display":" + ","reading":" + "},{"display":"ロールバック","reading":"ろーるばっく"},{"display":"手順","reading":"てじゅん"},{"display":"\n\n","reading":"\n\n"},{"display":"ポストモーテム","reading":"ぽすともーてむ"},{"display":"は","reading":"は"},{"display":"盛らずに","reading":"もらずに"},{"display":"書きます","reading":"かきます"},{"display":"。","reading":"。"},{"display":"自信だけ","reading":"じしんだけ"},{"display":"盛ります","reading":"もります"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (31, 'advanced', '#web-app', 'サトウ', '認証まわり、OAuth とセッションどっちで行く？', 'セッション + CSRF トークンで行きます。
OAuth は将来のスケール用に温存。
今はシンプルが最強アーキテクチャです。僕調べ。', 'せっしょん + CSRF とーくんでいきます。
OAuth はしょうらいのすけーるようにおんぞん。
いまはしんぷるがさいきょうあーきてくちゃです。ぼくしらべ。', '[{"display":"セッション","reading":"せっしょん"},{"display":" + ","reading":" + "},{"display":"CSRF ","reading":"CSRF "},{"display":"トークン","reading":"とーくん"},{"display":"で","reading":"で"},{"display":"行きます","reading":"いきます"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"OAuth","reading":"OAuth"},{"display":" は","reading":" は"},{"display":"将来の","reading":"しょうらいの"},{"display":"スケール","reading":"すけーる"},{"display":"用に","reading":"ように"},{"display":"温存","reading":"おんぞん"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"今は","reading":"いまは"},{"display":"シンプル","reading":"しんぷる"},{"display":"が","reading":"が"},{"display":"最強","reading":"さいきょう"},{"display":"アーキテクチャ","reading":"あーきてくちゃ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"僕調べ","reading":"ぼくしらべ"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (32, 'advanced', '#incident', 'タナカ', '`/health` が 503。ロードバランサから外され始めてる', 'ヘルスチェックが厳しすぎです。
閾値を `timeout_ms=3000` に緩めます。
死んでないのに殺されるの、僕あるあるです。', 'へるすちぇっくがきびしすぎです。
いきちを `timeout_ms=3000` にゆるめます。
しんでないのにころされるの、ぼくあるあるです。', '[{"display":"ヘルスチェック","reading":"へるすちぇっく"},{"display":"が","reading":"が"},{"display":"厳しすぎです","reading":"きびしすぎです"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"閾値","reading":"いきち"},{"display":"を","reading":"を"},{"display":" `","reading":" `"},{"display":"timeout_ms=3000","reading":"timeout_ms=3000"},{"display":"` ","reading":"` "},{"display":"に","reading":"に"},{"display":"緩めます","reading":"ゆるめます"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"死んでないのに","reading":"しんでないのに"},{"display":"殺されるの","reading":"ころされるの"},{"display":"、","reading":"、"},{"display":"僕","reading":"ぼく"},{"display":"あるあるです","reading":"あるあるです"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (33, 'advanced', '#customer-success', 'CS-ヤマダ', 'クライアントAが「CSVが文字化け」と怒り気味です', 'エンコーディングは Shift_JIS でした。UTF-8 に正規化します。
- 暫定: 再エクスポート
- 恒久: 文字コード明示

文字化けは心のデコードミス、ではありません。今回は本当にバイトです。', 'えんこーでぃんぐは Shift_JIS でした。UTF-8 にせいきかします。
- ざんてい: さいえくすぽーと
- こうきゅう: もじこーどめいじ

もじばけはこころのでこーどみす、ではありません。こんかいはほんとうにばいとです。', '[{"display":"エンコーディング","reading":"えんこーでぃんぐ"},{"display":"は","reading":"は"},{"display":" Shift_JIS ","reading":" Shift_JIS "},{"display":"でした","reading":"でした"},{"display":"。","reading":"。"},{"display":"UTF-8","reading":"UTF-8"},{"display":" に","reading":" に"},{"display":"正規化","reading":"せいきか"},{"display":"します","reading":"します"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"暫定","reading":"ざんてい"},{"display":": ","reading":": "},{"display":"再","reading":"さい"},{"display":"エクスポート","reading":"えくすぽーと"},{"display":"\n","reading":"\n"},{"display":"- ","reading":"- "},{"display":"恒久","reading":"こうきゅう"},{"display":": ","reading":": "},{"display":"文字コード","reading":"もじこーど"},{"display":"明示","reading":"めいじ"},{"display":"\n\n","reading":"\n\n"},{"display":"文字化け","reading":"もじばけ"},{"display":"は","reading":"は"},{"display":"心の","reading":"こころの"},{"display":"デコード","reading":"でこーど"},{"display":"ミス","reading":"みす"},{"display":"、","reading":"、"},{"display":"ではありません","reading":"ではありません"},{"display":"。","reading":"。"},{"display":"今回は","reading":"こんかいは"},{"display":"本当に","reading":"ほんとうに"},{"display":"バイト","reading":"ばいと"},{"display":"です","reading":"です"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (34, 'advanced', '#web-app', 'サトウ', 'フィーチャーフラグ、本番で消し忘れてない？', '`enable_beta_nav` は OFF です。確認済み。
トグルの監査ログも見ました。
忘れない自信があります。忘れっぽいですが。', '`enable_beta_nav` は OFF です。かくにんすみ。
とぐるのかんさろぐもみました。
わすれないじしんがあります。わすれっぽいですが。', '[{"display":"`","reading":"`"},{"display":"enable_beta_nav","reading":"enable_beta_nav"},{"display":"`","reading":"`"},{"display":" は ","reading":" は "},{"display":"OFF","reading":"OFF"},{"display":" です","reading":" です"},{"display":"。","reading":"。"},{"display":"確認","reading":"かくにん"},{"display":"済み","reading":"すみ"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"トグル","reading":"とぐる"},{"display":"の","reading":"の"},{"display":"監査","reading":"かんさ"},{"display":"ログ","reading":"ろぐ"},{"display":"も","reading":"も"},{"display":"見ました","reading":"みました"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"忘れない","reading":"わすれない"},{"display":"自信","reading":"じしん"},{"display":"があります","reading":"があります"},{"display":"。","reading":"。"},{"display":"忘れっぽいですが","reading":"わすれっぽいですが"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (35, 'advanced', '#random', 'タナカ', 'オンコール当番、今週の引き継ぎメモある？', 'ランブック更新済みです。
> まずメトリクス、次にロールバック

エスカレーションは僕→サトウ。僕が寝てたら叫んでください。', 'らんぶっくこうしんすみです。
> まずめとりくす、つぎにろーるばっく

えすかれーしょんはぼく→さとう。ぼくがねてたらさけんでください。', '[{"display":"ランブック","reading":"らんぶっく"},{"display":"更新","reading":"こうしん"},{"display":"済み","reading":"すみ"},{"display":"です","reading":"です"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"> ","reading":"> "},{"display":"まず","reading":"まず"},{"display":"メトリクス","reading":"めとりくす"},{"display":"、","reading":"、"},{"display":"次に","reading":"つぎに"},{"display":"ロールバック","reading":"ろーるばっく"},{"display":"\n\n","reading":"\n\n"},{"display":"エスカレーション","reading":"えすかれーしょん"},{"display":"は","reading":"は"},{"display":"僕","reading":"ぼく"},{"display":"→","reading":"→"},{"display":"サトウ","reading":"さとう"},{"display":"。","reading":"。"},{"display":"僕が","reading":"ぼくが"},{"display":"寝てたら","reading":"ねてたら"},{"display":"叫んでください","reading":"さけんでください"},{"display":"。","reading":"。"}]');
INSERT OR IGNORE INTO problems (id, difficulty, channel, sender, incoming_message, reply_text, reply_reading, reply_units) VALUES (36, 'advanced', '#web-app', 'サトウ', 'パフォーマンス目標、p95 200ms いける？', 'キャッシュレイヤ足せばいけます。
Redis 前提、ヒット率 90% 狙い。
レイテンシは僕の自信より低い数字で出します。', 'きゃっしゅれいやたせばいけます。
Redis ぜんてい、ひっとりつ 90% ねらい。
れいてんしはぼくのじしんよりひくいすうじでだします。', '[{"display":"キャッシュレイヤ","reading":"きゃっしゅれいや"},{"display":"足せば","reading":"たせば"},{"display":"いけます","reading":"いけます"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"Redis","reading":"Redis"},{"display":" ","reading":" "},{"display":"前提","reading":"ぜんてい"},{"display":"、","reading":"、"},{"display":"ヒット","reading":"ひっと"},{"display":"率","reading":"りつ"},{"display":" 90%","reading":" 90%"},{"display":" ","reading":" "},{"display":"狙い","reading":"ねらい"},{"display":"。","reading":"。"},{"display":"\n","reading":"\n"},{"display":"レイテンシ","reading":"れいてんし"},{"display":"は","reading":"は"},{"display":"僕の","reading":"ぼくの"},{"display":"自信より","reading":"じしんより"},{"display":"低い","reading":"ひくい"},{"display":"数字で","reading":"すうじで"},{"display":"出します","reading":"だします"},{"display":"。","reading":"。"}]');
